@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Sub-Talisman-Struct/project>
	deps:runtime-requirement         [ deps:on "MooX::Struct 0.016"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Sub::Talisman"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::NoWarnings"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

